from asyncpg.exceptions import UniqueViolationError

__all__ = ["UniqueViolationError"]
